### ISSUE TITLE
Add csv import tool

### ISSUE THREAD

**Issue by cypressf** [cypressf/mit-climate-data-viz#257]
The editor is useful, but we also need a tool to import new datasets from csv files. Let's call this the "csv import tool."

**Comment by cypressf** [comment]
Working on this on branch csv-uploader: https://github.com/cypressf/climate-risk-map/tree/csv-uploader

**Comment by cypressf** [comment]
Example UI in progress: https://svante3.mit.edu/uploader

frontend-only at the moment. doesn't do anything yet. I'm working on a "wizard" of sorts that will guide you through selecting the "county id" and "state id" columns, then selecting any data columns, then labeling the data columns with

- [x] name
- [x] short_name
- [x] description
- [x] units
- [x] start_date
- [x] end_date
- [x] data source description
- [x] data source link

![Screen Shot 2022-02-16 at 17 01 45](https://user-images.githubusercontent.com/443397/154364817-84cab063-e477-4ceb-9798-1fc50e731a4e.png)

**Comment by cypressf** [comment]
Made more progress on this today, enabled changing most of the metadata. Next steps:

- [x] units input
- [x] make upload endpoint on backend
  - [x] should this take the raw csv + some metadata, or should it take a parsed csv + metadata? if it takes the parsed csv, that requires the frontend to load the entire csv into memory which could be prohibitive or slow for very large csv files. if it sends the raw csv, I'll need to make sure I can send multiple "types" of things along with the request (the raw file + the metadata in json)
  - [x] create the parser on the backend, if necessary
  - [x] create the part of the backend that combines csv with metadata, and saves as new datasets, data sources
- [x] wire up frontend to backend
- [ ] make frontend pretty

**Comment by cypressf** [comment]
It looks like it's possible to send both the file and the metadata about it in the same HTTP request via a multipart form request. not going to use this library necessarily, but here's an example: https://stackoverflow.com/questions/50774176/sending-file-and-json-in-post-multipart-form-data-request-with-axios

**Comment by cypressf** [comment]
I made more progress on the UI. I added units endpoint and straightened up the input styles a bit.

![Screen Shot 2022-02-26 at 17 24 46](https://user-images.githubusercontent.com/443397/155860977-2e3ac45b-9671-43fc-ba9c-c73e54e0817b.png)
.

**Comment by cypressf** [comment]
actix-web has sparse out-of-the-box support for extracting structs from multipart forms, unlike its ability to extract data into structs for a json request body. In [this conversation on discord](https://canary.discord.com/channels/771444961383153695/771447545154371646/933405505928458240
), I learned theres a [library](https://github.com/robjtede/actix-multipart-derive) someone has worked on for this, but it's kinda broken so it's best to do things manually.

This is mildly frustrating because it means I need to manually read the fields from the multipart stream, and handle the file and the metadata myself.

**Comment by cypressf** [comment]
I'm done with work for the day, but I [posted a question in the discord thread](https://canary.discord.com/channels/771444961383153695/933405505928458240/948697759744151554) and my next plan is to investigate using [awmp](https://crates.io/crates/awmp) to send some text fields and a file over in one go. If that's not the way, then I could potentially roll-my-own solution by using the [actix-multipart](https://docs.rs/actix-multipart/latest/actix_multipart/index.html) library to manually read the fields, including the file.

Considerations

- [ ] do I need to parse the whole file into memory at once in order to transform it into a format I can insert into the database, or can I parse it chunk-by-chunk? What about if I force people to upload files with a format that better matches the columns in the database?
- [ ] can I use awmp to retrieve json-structured metadata as a rust struct, or do I need to send all fields over as text?
- [ ] what are my file-size limitations if I read it into memory?
- [ ] Whats the maximum file size I can just urlencode, or send as a json body?

**Comment by cypressf** [comment]
Even if I use awmp I can't send metadata in json form, so I can't send back an array of column specifiers. Instead, I'd have to send metadata as key/value pairs, where each value is text. Since there's a variable number of column specifiers, I would need to come up with a standard naming convention. This is annoying.

It'd be simpler to serialize the metadata and store it all in  _one_ of the fields—let's call it `metadata`—and deserialize that field with serde on the rust end. Then send the file in another field—let's call it `file`. That way we could send the metadata and file in one request relatively sanely. I just need to figure out how to serialize and deserialize the text, which shouldn't be too bad.

Inspired by https://stackoverflow.com/questions/18240692/is-using-multipart-form-data-any-better-then-json-base64

**Comment by cypressf** [comment]
# Progress

- I added a dummy endpoint to the backend that accepts metadata and a file. it successfully parses the metadata via serde from a multipart form text field
- I added a submit button to the frontend to send the metadata and file to that dummy endpoint (currently, it just responds with the metadata it received)

# TODO

- [x] investigate alternative ways to validate form
   - perhaps tie validator to mui components
   - perhaps we don't need to validate if strings are > 0 length because the components already check that for us
- [x] save data to database
- [ ] figure out how to specify api url relative to base api url. currently we're specifying the entire thing
- [x] preview data while uploading

**Comment by cypressf** [comment]
I'll use the rust [`csv`](https://docs.rs/csv/1.1.6/csv/) library to parse the csv file from the multpart data.

**Comment by cypressf** [comment]
In order to read a csv file with column names and types specified at runtime, I will try something similar to the strategy here: https://stackoverflow.com/questions/64369887/how-do-i-read-csv-data-without-knowing-the-structure-at-compile-time

**Comment by cypressf** [comment]
I'm having trouble reading the awmp file. I'm grabbing the file object from parts.files, getting its inner NamedTempFile, and iterating through it, but it seems to be empty. This is curious because calling persist seems to work on it.

**Comment by cypressf** [comment]
For some reason, using `csv::Reader::from_path(file.into_inner().path())` works whereas `csv::Reader::from_reader(file.into_inner())` doesn't work. The latter seems more direct, since I'd expect the file object to already contain the file reference, and it seems redundant to pass the csv reader the path to the file, and have a it read it again.

**Comment by cypressf** [comment]
Calling reopen on the file [as seen here](https://docs.rs/tempfile/latest/tempfile/#examples) also works. Perhaps it cannot be read directly and needs to be reopened for some reason.

**Comment by cypressf** [comment]
Besides simply missing data, I need to make checks to ensure the validity of the new data being uploaded:

- [x] data columns exist. on error: `400 missing columns: {names of missing columns}`
- [x] state and county columns exist. on error: `400 missing columns: {names of missing columns}`
- [x] datasets with the same names or short names do not already exist in the database. on error: `400 datasets already exist: {names of duplicate datasets}`
- [x] county and state ids are all valid. on error: `400 invalid county ids: {invalid county ids}, invalid state ids: {invalid state ids}`
- [x] data with the same (dataset, source, start date, end date, county id, state id) combo does not exist. on error: `400 duplicate data for {data}` (limit to first duplicate)
- [x] data source with the same name does not already exist. on error: `400 data source already exsists: {name of data source}`
- [x] data source is missing name, description, or link. on error: `400 data source needs a name, description, and link`
- [x] data source has a valid url. on error: `400 data source must have a valid url`

All of this error detection must be done before anything is inserted into the database, or all the database inserts must be part of a single transaction that can roll back, so the data isn't inserted partially and left in a bad state.

**Comment by cypressf** [comment]
- [x] allow adding datasets to existing sources

**Comment by cypressf** [comment]
# Ignore geo ids that aren't in the `geo_id` table

In order to do this, I think it would be most efficient to let the database decide. `data` already has a foreign key constraint on `geo_id` that will make an insert query fail if it contains invalid ids. I just need to construct a query that filters out those invalid ids instead of failing on them. One approach is to join the data being inserted with the `geo_id` table sort of like [this stack overflow post](https://stackoverflow.com/questions/42355651/how-to-ignore-rows-that-violate-foreign-key-constraint-in-postgres-insert-into).

**Comment by cypressf** [comment]
Another option is to use the [`ON CONFLICT`](https://www.postgresql.org/docs/14/sql-insert.html#SQL-ON-CONFLICT) clause

**Comment by cypressf** [comment]
Oh, I was mistaken. ON CONFLICT [only applies to unique or exclusion constraint violations](https://dba.stackexchange.com/a/294059/143596), not foreign key violations.

**Comment by cypressf** [comment]
Instead of ignoring invalid geo ids, I'm going to report them to the uploader so they can modify their csv file if they so desire.
